[build]
    command = "CI= npm run build"
    publish="/build"
    base = "/"
    build = "build"
    

[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200

[[plugins]]
  package  = "@netlify/plugin-a11y"